name: goboscript-test
description: Action that tests your goboscript repository's /test/ project, and installs dependencies using inflator.
branding:
  icon: check-circle
  color: yellow
  
runs:
  using: "composite"
  permissions:
    contents: write
  
  steps:
    - name: Test with option 'build'
      shell: bash
      run: |
        echo ${INPUT_BUILD}
  
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    
    - name: Set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      
    - name: Set up goboscript
      shell: bash
      run: |
        export PATH="$PATH:~/.local/bin"
        export PATH="$PATH:~/.cargo/bin"
        
        cargo install --git https://github.com/aspizu/goboscript

      # above code is from:
      # run: curl -fsSL https://raw.githubusercontent.com/aspizu/goboscript/refs/heads/main/install.sh | sh
      # but backpack and sb2gs have been removed
    - name: Install dependencies for testing
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -U turbowarp-cli
        pip install -U inflator

    - name: Install playwright
      shell: bash
      run: playwright install --with-deps chromium

    - name: Inflate
      shell: bash
      run: |
        ls -l
        
        inflate install .  # inflate gobo
        cd test
        inflate install -r inflator.toml  # inflate test dependencies, e.g. assert
        inflate

    - name: Build
      shell: bash
      run: |
        cd test
        goboscript build

    - name: Commit test.sb3
      uses: EndBug/add-and-commit@v9
      with:
        add: "test/test.sb3 --force"
        message: 'build: test.sb3'

    - name: Test with tw-cli
      shell: bash
      run: |
        cd test
        ls -l
        twcli run ./test.sb3

